# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.data_data set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.aishiteitanoni.node.5_model] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.item_display_5_model set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.aishiteitanoni.node.2_model] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.item_display_2_model set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.aishiteitanoni.node.3_model] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.item_display_3_model set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.aishiteitanoni.node.6_model] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.item_display_6_model set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.aishiteitanoni.node.centre_model] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.item_display_centre_model set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.aishiteitanoni.node.1_model] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.item_display_1_model set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.aishiteitanoni.node.4_model] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.item_display_4_model set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.aishiteitanoni.node.shadow1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.item_display_shadow1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.aishiteitanoni.node.shadow2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.item_display_shadow2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.aishiteitanoni.node.shadow3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.item_display_shadow3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.aishiteitanoni.node.white1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.item_display_white1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.aishiteitanoni.node.white2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.item_display_white2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.aishiteitanoni.node.white3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.item_display_white3 set from storage aj:uuid main.out