# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.aishiteitanoni.root] run return 0
execute on passengers if entity @s[tag=aj.aishiteitanoni.data] unless data entity @s {data:{rigHash: 'acfcc34f0916627ce62cfce271a5f9ce68ea2e63d157bd2cf6932bf6b05dc0d1'}} on vehicle run function animated_java:aishiteitanoni/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1