# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.aishiteitanoni.root] run return 0
execute unless score @s aj.is_rig_loaded matches 1 run function #animated_java:global/root/on_load
function #animated_java:aishiteitanoni/as_root/pre_tick
execute if entity @s[tag=aj.aishiteitanoni.animation.spawn.playing] run function animated_java:aishiteitanoni/animations/spawn/zzz/on_tick
execute if entity @s[tag=aj.aishiteitanoni.animation.spawn_short.playing] run function animated_java:aishiteitanoni/animations/spawn_short/zzz/on_tick
execute on passengers if entity @s[tag=aj.aishiteitanoni.data] run function animated_java:aishiteitanoni/root/zzz/1
execute at @s on passengers run rotate @s ~ ~
function #animated_java:aishiteitanoni/as_root/post_tick