# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.aishiteitanoni.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'aishiteitanoni', 'function_path': 'animated_java:aishiteitanoni/animations/spawn_short/next_frame'}
execute if score @s aj.spawn_short.frame matches 40.. run scoreboard players set @s aj.spawn_short.frame 1
execute store result storage aj:temp frame int 1 run scoreboard players get @s aj.spawn_short.frame
execute at @s run function animated_java:aishiteitanoni/animations/spawn_short/zzz/apply_frame with storage aj:temp
scoreboard players add @s aj.spawn_short.frame 1