# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard objectives add aj.spawn.frame dummy
scoreboard objectives add aj.spawn_short.frame dummy